import hashlib
import os
from pypdf import PdfReader
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv

load_dotenv()

# Using Gemini 2.5 for high-precision forensics
MODEL_FORENSICS = "gemini-2.5-flash" 

_api_key = os.getenv("GOOGLE_API_KEY")

class DocumentForensics:
    def __init__(self):
        self.llm = ChatGoogleGenerativeAI(
            model=MODEL_FORENSICS,
            google_api_key=_api_key,
            temperature=0.1,  # Low temp for factual consistency
        )

    def calculate_hash(self, file_path: str) -> str:
        sha256_hash = hashlib.sha256()
        with open(file_path, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()

    async def analyze_document(self, file_path: str) -> dict:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Document not found: {file_path}")

        reader = PdfReader(file_path)
        metadata = reader.metadata or {}
        anomalies = []

        # --- 1. Metadata Analysis (Context Aware) ---
        software_used = (metadata.get("/Producer", "") or metadata.get("/Creator", "") or "Unknown")
        
        # Aadhaar documents are often generated by e-Aadhaar systems or specific encoders
        # We only flag if we see PURE image editors like Photoshop/GIMP
        FORGERY_TOOLS = ["Photoshop", "GIMP", "Affinity", "Inkscape"]
        
        metadata_flag = False
        if any(tool.lower() in software_used.lower() for tool in FORGERY_TOOLS):
            metadata_flag = True
            # Hum ise direkt anomaly nahi bolenge, AI ko context denge

        # --- 2. Advanced AI Analysis (Gemini 2.5 Prompt) ---
        # PDF se text extract kar rahe hain
        text_parts = [page.extract_text() or "" for page in reader.pages[:1]]
        text_content = "".join(text_parts).strip()

        # Detailed prompt for Gemini 2.5 to reduce False Positives
        prompt = f"""
        You are a Document Forensics Expert. Analyze this content from an Indian Aadhaar PDF.
        
        DOCUMENT TEXT:
        {text_content}
        
        METADATA INFO:
        Software: {software_used}
        
        TASKS:
        1. Check if the name, DOB, and Aadhaar number format are consistent.
        2. Identify if the metadata '{software_used}' is normal for a government-issued PDF or suggests manual tampering.
        3. Look for 'logic' errors (e.g., Issue date vs DOB mismatch).
        
        DANGER: Do NOT flag as FORGED just because it's a digital copy. Only flag if there is evidence of human alteration.
        
        RESPONSE FORMAT (JSON ONLY):
        {{
            "verdict": "GENUINE" | "SUSPICIOUS" | "FORGED",
            "confidence": 0-100,
            "reasoning": "Brief explanation",
            "anomaly_type": "None" | "Metadata" | "Textual Inconsistency"
        }}
        """

        ai_response = await self.llm.ainvoke(prompt)
        # Parse the JSON response from Gemini
        import json
        try:
            # Safely extract JSON from the AI response string
            cleaned_content = ai_response.content.replace("```json", "").replace("```", "").strip()
            res = json.loads(cleaned_content)
        except:
            # Fallback if JSON parsing fails
            res = {"verdict": "SUSPICIOUS", "confidence": 50, "reasoning": "AI response parsing error", "anomaly_type": "System"}

        # --- 3. Final Verdict Mapping ---
        final_anomalies = []
        if res["verdict"] != "GENUINE":
            final_anomalies.append({
                "type": res["anomaly_type"],
                "detail": res["reasoning"],
                "severity": "high" if res["verdict"] == "FORGED" else "medium"
            })

        return {
            "status": res["verdict"],
            "confidence": res["confidence"],
            "anomalies": final_anomalies,
            "hash_verification": {
                "sha256": self.calculate_hash(file_path)[:32] + "...",
                "is_valid": res["verdict"] != "FORGED"
            },
            "metadata": {
                "software": software_used,
                "author": metadata.get("/Author", "Government of India"),
                "pdf_version": reader.pdf_header
            }
        }

forensics_engine = DocumentForensics()